In [1]:
!pip install --upgrade pip

     |████████████████████████████████| 1.5MB 4.3MB/s eta 0:00:01
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3


In [3]:
import tensorflow as tf
print(tf.__version__)

2.1.0


In [5]:
!pip show tensorflow

In [6]:
import tensorflow as tf

In [7]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [9]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.25506586,  0.19196957,  0.20852123,  0.16427891, -0.8443515 ,
         0.23492953,  0.05443726, -0.6232743 ,  0.24863845, -0.04257336]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.123616  , 0.11605726, 0.11799418, 0.11288764, 0.04117217,
        0.12115172, 0.10114462, 0.05135898, 0.12282401, 0.09179343]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

2.1107118

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 4s 67us/sample - loss: 0.2930 - accuracy: 0.9155
Epoch 2/5
60000/60000 [==============================] - 3s 49us/sample - loss: 0.1423 - accuracy: 0.9571
Epoch 3/5
60000/60000 [==============================] - 3s 49us/sample - loss: 0.1081 - accuracy: 0.9668
Epoch 4/5
60000/60000 [==============================] - 3s 50us/sample - loss: 0.0873 - accuracy: 0.9727
Epoch 5/5
60000/60000 [==============================] - 3s 48us/sample - loss: 0.0735 - accuracy: 0.9770


In [15]:
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 0s - loss: 0.0750 - accuracy: 0.9773


[0.07502034245829564, 0.9773]

In [16]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.3196416e-08, 1.2190898e-09, 2.4595745e-06, 1.7820304e-04,
        2.6488864e-10, 5.9227965e-08, 5.5985117e-14, 9.9981350e-01,
        8.1537115e-07, 4.8589959e-06],
       [1.2686700e-08, 3.6740868e-04, 9.9962711e-01, 1.8125660e-06,
        3.1253739e-15, 3.4079508e-06, 1.0559559e-07, 1.9347885e-13,
        1.5229870e-07, 3.4833515e-14],
       [4.1694798e-07, 9.9874520e-01, 2.0336593e-05, 1.5925334e-05,
        6.6062523e-05, 3.6195045e-06, 2.6223604e-05, 8.4193167e-04,
        2.7441888e-04, 5.9740282e-06],
       [9.9995530e-01, 3.5419548e-10, 2.9123660e-06, 2.0439596e-07,
        4.2832224e-07, 2.0407431e-06, 3.0603194e-05, 8.8331694e-07,
        5.9953917e-09, 7.6258561e-06],
       [1.0194501e-06, 7.2999910e-08, 1.6497917e-05, 3.6605702e-08,
        9.9897087e-01, 4.2204405e-08, 4.1183853e-07, 2.9517383e-05,
        5.9596732e-07, 9.8097324e-04]], dtype=float32)>